### ISSUE TITLE
Add support for Directus 9

### ISSUE THREAD

**Issue by maartenvn** [maartenvn/directus-8-conditional-fields#2]
Add support for Directus 9

**Comment by TomasSestak** [comment]
Will this be available?

**Comment by maartenvn** [comment]
Directus 9 support will come in a separate extension/repository, once Directus v9 is officially released and the extension API is finalized.

**Comment by TomasSestak** [comment]
I found out there is possibility to imitate this funcionality with repeators if anyone would wondering

**Comment by rickysullivan** [comment]
> I found out there is possibility to imitate this funcionality with repeators if anyone would wondering

I am wondering.

**Comment by mateomm22** [comment]
> I found out there is possibility to imitate this funcionality with repeators if anyone would wondering

I am wondering also.

**Comment by maartenvn** [comment]
Closing this as Directus has native support for Conditional fields now :slightly_smiling_face: 

(https://github.com/directus/directus/pull/6864)
